version: '2'

services:
  # flower
  flower:
    image: mher/flower
    container_name: flower
    network_mode: host
    restart: always
    command: --address=0.0.0.0 --port=5555 --broker=redis://dnode20:6379/1
